name:                genderhs
version:             0.1.0.0
github:              "githubuser/genderhs"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/genderhs#readme>

dependencies:
- base >= 4.7 && < 5
- filepath
- directory
- http-conduit
- xml-conduit
- html-conduit
- binary-conduit
- xml-types
- tar-conduit
- conduit-extra
- conduit
- resourcet
- mtl
- text
- bytestring
- gnuplot
- wave
- containers
- pure-fft
- binary
library:
  source-dirs: src

executables:
  genderhs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - genderhs

tests:
  genderhs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - genderhs
